### ISSUE TITLE
Wo finde ich die IDs der Fernsehsender?

### ISSUE THREAD

**Issue by HDValentin** [Axel-Erfurt/TV-Tagesprogramm#2]
Im Quelltext wird erwähnt, wo man die IDs für die Sender findet.
http://test.mobil.hoerzu.de/tv-sender/ ist nicht mehr verfügbar.

Gibt es eine andere Quelle für die IDs?

**Comment by Axel-Erfurt** [comment]
Etwas umständlich, aber wohl die einzige Möglichkeit

getestet mit Firefox

https://www.hoerzu.de/tv-programm/jetzt/

aufrufen, dann Extras -> Seiteninformationen -> Medien

die Logos beginnen mit _https://sender.epglogos.de_ , die ID ist der Dateiname, also 38.png RTL

Den Sender mußt Du halt am Logo erkennen.

![hoerzu](https://github.com/Axel-Erfurt/TV-Tagesprogramm/assets/2623542/993c0e61-c8d7-439b-a672-bf4ba8e0b850)

**Comment by HDValentin** [comment]
Vielen Dank, das ist sehr hilfreich

**Comment by HDValentin** [comment]
Kanal-Liste extended:

'ard': 71, 
'zdf': 37, 
'zdf neo': 659, 
'zdf info': 276, 
'arte': 58, 
'wdr': 46, 
'ndr': 47, 
'mdr': 48, 
'hr': 49, 
'swr': 50, 
'swr': 10142, 
'br': 51, 
'sr': 12052, 
'rbb': 52, 
'3sat': 56, 
'alpha': 104, 
'kika': 57, 
'phoenix': 194, 
'tagesschau 24': 100, 
'one': 146, 
'rtl': 38, 
'sat 1': 39, 
'pro 7': 40, 
'rtl plus': 12033, 
'kabel 1': 44, 
'rtl 2': 41, 
'vox': 42, 
'rtl nitro': 763, 
'n24 doku': 12045, 
'ntv': 66, 
'kabel 1 doku': 12043, 
'sport 1': 64, 
'eurosport 1': 65,
'esports': 12102,
'super rtl': 43, 
'sat 1 gold': 774, 
'vox up': 12125, 
'rtl up': 12033, 
'welt der wunder': 135946,
'home und garden tv': 12105,
'sixx': 694, 
'sixx': 769, 
'servus tv': 660,
'servus tv': 770, 
'welt': 175, 
'euronews': 68, 
'bild': 146, 
'orf 1': 54, 
'orf 2': 55, 
'orf 3': 56, 
'orf 3': 757, 
'tele 5': 277, 
'7maxx': 783, 
'dmaxx': 507, 
'dw': 300, 
'fox': 565, 
'srf 1': 59, 
'srf 2': 60, 
'srf info': 231, 
'disney': 139, 
'nickelodeon': 485, 
'comedy central': 532, 
'tlc': 135954, 
'deluxe music': 511, 
'dt. musik fernsehen': 570, 
'tv berlin': 1192, 
'franken fernsehen': 151, 
'hamburg 1': 153, 
'münchen tv': 262, 
'rnf': 211, 
'rheinmain tv': 403, 
'spreekanal': 236, 
'bbc world news': 67, 
'cnn': 69, 
'cnbc': 538
